[package]
name = "inverted-index"
version = "0.1.0"
authors = ["Sushant Rana <sushant.rana31@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "0.9.2"
bson = "0.14.0"